# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
# Skriver ut information om matrisen
print("Dimension (axes):", A.ndim)       # Antal dimensioner/axlar
print("Shape:", A.shape)                # Form (rader, kolumner)
print("Size:", A.size)                  # Totalt antal element
print("Datatype:", A.dtype)             # Datatyp för elementen

Dimension (axes): 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
# Elementvis subtraktion
elementwise_subtraction = B - C
print("Elementwise Subtraction (B - C):")
print(elementwise_subtraction)
print()

Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]



In [6]:
# Elementvis multiplikation
elementwise_multiplication = B * C
print("Elementwise Multiplication (B * C):")
print(elementwise_multiplication)
print()

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]



In [7]:
# Matris-multiplikation (använder @-operatorn)
matrix_multiplication = B @ C
print("Matrix Multiplication (B @ C):")
print(matrix_multiplication)

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Exponentierar varje element i matrisen
exp_B = np.exp(B)
print("Exponentiate each element (np.exp):")
print(exp_B)
print()

Exponentiate each element (np.exp):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]



In [10]:
# Beräknar det minsta värdet i hela matrisen
min_value = B.min()
print("Minimum value in the whole matrix:")
print(min_value)
print()

Minimum value in the whole matrix:
1



In [11]:
# Beräknar det minsta värdet i varje rad
min_in_rows = B.min(axis=1)
print("Minimum value in each row:")
print(min_in_rows)
print()

Minimum value in each row:
[1 4 7]



In [12]:
# Beräknar det minsta värdet i varje kolumn
min_in_columns = B.min(axis=0)
print("Minimum value in each column:")
print(min_in_columns)
print()

Minimum value in each column:
[1 2 3]



In [13]:
# Index för det minsta värdet i hela matrisen
index_min = np.argmin(B)
print("Index of minimum value in the whole matrix:")
print(index_min)
print()

Index of minimum value in the whole matrix:
0



In [14]:
# Index för det minsta värdet i varje rad
index_min_rows = np.argmin(B, axis=1)
print("Index of minimum value in each row:")
print(index_min_rows)
print()

Index of minimum value in each row:
[0 0 0]



In [15]:
# Summan av alla element i matrisen
sum_elements = B.sum()
print("Sum of all elements:")
print(sum_elements)
print()

Sum of all elements:
45



In [16]:
# Medelvärdet för varje kolumn
mean_columns = B.mean(axis=0)
print("Mean for each column:")
print(mean_columns)
print()

Mean for each column:
[4. 5. 6.]



In [17]:
# Medianen för varje kolumn
median_columns = np.median(B, axis=0)
print("Median for each column:")
print(median_columns)

Median for each column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [18]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
När man skriver färre index än matrisen har dimensioner då väljs det automatiskt alla värden i de andra dimensionerna.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [20]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [22]:
for element in np.nditer(A):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [23]:
for element in A.flatten():
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [24]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
Förklaring: 
a är en 1D-array med 30 element. 
form (2, 3, -1) betyder att med 2:Första axeln (block) ska ha 2 block, 3:Andra axeln (rader) ska ha 3 rader per block. 
-1:NumPy räknar automatiskt ut storleken på tredje axeln (kolumner) baserat på antalet element. Här är det 30÷(2×3)=5, så tredje axeln får 5 kolumner.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)